Bluetooth: btqca: Fixed a coding style error
Fixed this coding style erro

./drivers/bluetooth/btqca.c:84: ERROR: code indent should use tabs where possible

Signed-off-by: Joan Jani <igiann@hotmail.com>
Change-Id: I65db3f4a06f177a3358e0d6f0542ef4b0ebf25b5
Signed-off-by: Marcel Holtmann <marcel@holtmann.org>
(cherry picked from commit 2193a9800b1d6ae771539e1cdae1e7340b9d90ea)
Signed-off-by: TogoFire <togofire@mailfence.com>