Revert "wifi: rtl8xxxu: RTL8192EU always needs full init"
This reverts commit 017de36f2ae657784eacf045413515297193a500.

- Fix error in struct field designator
log:
../drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_8192e.c:1703:3: error: field designator 'needs_full_init' does not refer to any field in type 'struct rtl8xxxu_fileops'
        .needs_full_init = 1,
        ~^~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: TogoFire <italomellopereira@gmail.com>
Change-Id: Id5bdc7044b62412d539a60f368f4b0f9180fd6e8